### ISSUE TITLE
Secure financial and in-kind sponsorship

### ISSUE THREAD

**Issue by julianpistorius** [resbazaz/festival2024#10]
## Tasks

- [x] Confirm what we will need (i.e. venue hire, tents, catering) - @resbazaz/festival2024
- [x] Draft standard email template - lead by @lwdozal?
- [x] Compile list of potential sponsors - @resbazaz/festival2024
- [x] Identify best-placed team member to approach each potential sponsor - @resbazaz/festival2024
- [x] For each sponsor and team member combination: Team member to write organizer a personal email based on standard email template

**Comment by lwdozal** [comment]
Really rough draft of financial support email template:

# Financial Support Email

*Subject:* ResBaz2024 Financial Sponsorship Inquiry

Hello [name],


I am [your name here], a member of the ResBaz AZ 2024 festival organizing committee. [[ResBaz AZ](http://arizona.researchbazaar.org/)](http://arizona.researchbazaar.org/), short for Research Bazaar Arizona, is a community and an annual festival-style event that promotes data science literacy across Arizona. 


The 5th annual ResBaz AZ festival is happening from May 15th-17th, 2024. This free, community driven, and highly collaborative event provides members of the university and surrounding communities with opportunities to “level up” in computational and digital tools for research.


Although we offer the festival free of charge because of timeless volunteer work, there are still some financial barriers left. For example, conference refreshments and University facilities labor fees for set-up. Your financial  or in-kind sponsorship can provide a comfortable and collaborative learning environment for researchers across campus.


Any contribution is greatly appreciated and in return your organization will be featured on our website and other promotional materials. 


Thank you for your support,
[your name here]
http://arizona.researchbazaar.org/

**Comment by TinaJAZ** [comment]
Yes, I know. I missed an important meeting. But, I have questions.  To help plan and better solicit funds, are you not asking people to register in advance? I know that registration has always been a contentious topic.

You are aware of the financial situation UArizona is in right now? You are leaving money on the table if you cannot provide an account of registration and in-person attendance. About how many people are you expecting for lunch, snacks, and after event get together?

Where are the in-person events taking place?

Asking for any contribution amount is too open to interpretation. How much money do you need and for what will the funds pay?

Most companies want to know what they are sponsoring – an event that annually attracts how many people, how much does “comfort” cost, refreshments for how many people on what days, logo placement on day-of, in-person events, and facilities labor fees for setup?

How much has the 3-day with 2 days in person cost in the past?

Free lunch for the first 50 registrants who attend in-person?

Are you asking for corporate support from the volunteers’ workplace?
Is there a list or companies who have supported in the past?

Example, low guestimates for those who registered:
May 15: Online Conference
May 16: Unconference in-person
Lunch sponsor for 50 people x $22 = $1,100
Snack morning 50 x $18 = $900 ea
Snack afternoon 50 x $18 = $900 ea
May 17: Traditional Conference in-person
Lunch sponsor for 50 people x $22 = $1,100
Snack morning 50 x $18 = $900 ea
Snack afternoon 50 x $18 = $900 ea
After event 50 x $25 = $1,250, plus $250 room rental = $1,500


From: Laura W. Dozal ***@***.***>
Sent: Wednesday, March 6, 2024 4:04 PM
To: resbazaz/festival2024 ***@***.***>
Cc: Johnson, Tina L - (tina) ***@***.***>; Team mention ***@***.***>
Subject: [EXT]Re: [resbazaz/festival2024] Secure financial and in-kind sponsorship (Issue #10)


External Email

Really rough draft of financial support email template:

Financial Support Email

Subject: ResBaz2024 Financial Sponsorship Inquiry

Hello [name],

I am [your name here], a member of the ResBaz AZ 2024 festival organizing committee. [ResBaz AZ<http://arizona.researchbazaar.org/>](http://arizona.researchbazaar.org/), short for Research Bazaar Arizona, is a community and an annual festival-style event that promotes data science literacy across Arizona.

The 5th annual ResBaz AZ festival is happening from May 15th-17th, 2024. This free, community driven, and highly collaborative event provides members of the university and surrounding communities with opportunities to “level up” in computational and digital tools for research.

Although we offer the festival free of charge because of timeless volunteer work, there are still some financial barriers left. For example, conference refreshments and University facilities labor fees for set-up. Your financial or in-kind sponsorship can provide a comfortable and collaborative learning environment for researchers across campus.

Any contribution is greatly appreciated and in return your organization will be featured on our website and other promotional materials.

Thank you for your support,
[your name here]
http://arizona.researchbazaar.org/

**Comment by val-pf** [comment]
Hello @TinaJAZ 
We are opening registration next week, on Monday, together with the formal announcement of the ResBaz 2024 Conference dates & format.
In the past, we have had snacks and coffee during the conference, not the kind of full catering you describe. For example, last year, we had coffee and breakfast snacks, which amounted to less than 200$ for the day. We also had pizza sponsored for an evening event, similarly lower in amount. This was made possible through sponsorship of the same groups we are contacting now. I have not been involved in the conversations around sponsoring last year, but it was certainly agreed that there would be a form of sponsorship before we had final sign up numbers or attendee lists available. While I believe the details of the specific support were not established until much closer to the conference, the nature of the support was. Further, my understanding is that we are not trying to cold-acquire funding from random parties, but instead, contact established partners that have contributed to ResBaz's success in the past, through financial and other forms of support, and who are familiar with the concept and vision we pursue, and the benefits our conference brings to the local community.

**Comment by hidyverse** [comment]
I understand I'm responsible to email the sponsors: UA ICDI, DSI, and Libraries. 
Based on the conversation here, I will start putting some data together from at least our 2023 event, to add to our requests. 

I am holding off on sending until I get more details from logistics since DSI could confirm use of Cyverse tents and library will need to confirm use of rooms if requested.

**Comment by TinaJAZ** [comment]
I do not understand what “DSI could confirm use of CyVerse tents” means. Who is looking into CyVerse tents?


From: Heidi Steiner ***@***.***>
Sent: Monday, March 11, 2024 5:40 PM
To: resbazaz/festival2024 ***@***.***>
Cc: Johnson, Tina L - (tina) ***@***.***>; Mention ***@***.***>
Subject: [EXT]Re: [resbazaz/festival2024] Secure financial and in-kind sponsorship (Issue #10)


External Email

I understand I'm responsible to email the sponsors: UA ICDI, DSI, and Libraries.
Based on the conversation here, I will start putting some data together from at least our 2023 event, to add to our requests.

I am holding off on sending until I get more details from logistics since DSI could confirm use of Cyverse tents and library will need to confirm use of rooms if requested.

**Comment by hidyverse** [comment]
Hi Tina - we are looking to host our in-person days inside and outside. There was some talks that CyVerse may have old tents they could borrow us as a form of sponsorship. I will need more details on this before I send a request. I don't think anyone is currently looking into it.

**Comment by TinaJAZ** [comment]
Hi Heidi,
When I connected with Tina Lee in CyVerse, she said that CyVerse bought the tents for ResBaz and Julian asked about the tents earlier.  Also, ResBaz should connect with Andy Edmonds to get into the Keating basement to get the tents.

Full disclosure, I am not going into anyone’s basement for anything. That action calls for someone else to take the lead. Perhaps, Julian has already followed up on the tents?

/Tina

---I understand that my working hours may not coincide with your working hours. If you’re receiving this email outside of your typical working hours, please feel no pressure to read or respond until your schedule and workload permit.
- - - - -
Tina L. Johnson, M.A. l Data Science Institute l University of Arizona l BSRL Bldg #242 l 1230 N. Cherry Avenue l Tucson, AZ  85721 l ***@***.******@***.***>

The University of Arizona Land Acknowledgement<https://click.comms.arizona.edu/?qs=01d495226a505688f5f9533aa03bd018a3d782e827f7f2afce9e268fb9269ba5a58c868c992404dddce1b0d559509d522de41259d3efe9253c019cc6f910b405>
This message (including any attachments) may contain confidential, proprietary, privileged and/or private information.  If you are not the intended recipient of this message, please notify the sender immediately and delete the message and any attachments. Any disclosure, reproduction, distribution or other use of this message or any attachments by an individual or entity other than the intended recipient(s) is prohibited.

From: Heidi Steiner ***@***.***>
Sent: Tuesday, March 12, 2024 3:22 PM
To: resbazaz/festival2024 ***@***.***>
Cc: Johnson, Tina L - (tina) ***@***.***>; Mention ***@***.***>
Subject: [EXT]Re: [resbazaz/festival2024] Secure financial and in-kind sponsorship (Issue #10)


External Email

Hi Tina - we are looking to host our in-person days inside and outside. There was some talks that CyVerse may have old tents they could borrow us as a form of sponsorship. I will need more details on this before I send a request. I don't think anyone is currently looking into it.

**Comment by julianpistorius** [comment]
Thanks for looking into it @TinaJAZ. I had sent a message to @tyson-swetnam about the tents, and he said he'd check. I'll reach out to him & Andy Edmonds.

**Comment by TinaJAZ** [comment]
@julianpistorius Is there an update on the request for support of the after hours activity? Does ResBaz plan to request support from DSI? If so, what are the details so I can help to facilitate?

**Comment by julianpistorius** [comment]
I can ask Jetstream2 folks if they are interested in sponsoring this event.

**Comment by julianpistorius** [comment]
> @julianpistorius Is there an update on the request for support of the after hours activity? Does ResBaz plan to request support from DSI? If so, what are the details so I can help to facilitate?

@TinaJAZ please check with @hidyverse. She tagged herself to work with DSI.

As for tents - they have not been located. I suggest we let it go. So go ahead with your emails @hidyverse.

**Comment by TinaJAZ** [comment]
Great! To work with DSI means to work with me directly regarding support from DSI. @hidyverse what's on your mind about this? After hours support is a lot trickier and still requires documentation. In-person on campus support could be better and more manageable. Let's connect soon and make some suggestions for decisions.

**Comment by hidyverse** [comment]
Hi @TinaJAZ I've emailed Nirav and Maliaca directly the request. I tried to support all the numbers, as you mentioned above. Thanks for the tips! 

I requested: 
Coffee for 25-50 people on both Thursday and Friday 
Snacks for 25-50 people on both Thursday and Friday
A vinyl poster of the ResBaz AZ logo to direct traffic to our event (~$40 on [48hrprint.com](http://48hrprint.com/))
Printing ~15-30 paper fliers for distributing around UArizona campus (+4 laminated for HSIB)

No lunches are in discussion. We are going to other sponsors for off-campus requests. Let me know if we should touch base about any of these requests.

**Comment by hidyverse** [comment]
I'm compiling the list in discussion #23

**Comment by TinaJAZ** [comment]
@hidyverse Let me know when someone on the committee from UA is ready to place the orders and pay the bills. I'll provide the account number.

**Comment by val-pf** [comment]
done.
